### ISSUE TITLE
No "provides" tags available while configuring a module-info

### ISSUE THREAD

**Issue by xinyingho** [moditect/moditect#110]
When configuring a module-info for a particular module, we can add _exports_, _opens_ and _uses_ tags but there aren't any _provides_ tags available to declare SPI implementations (service provider interface).

For instance, I'd like to be able to do something like this:
```
<module>
  <moduleInfo>
    <name>myModule</name>
    <exports>org.test.myClass</exports>
    <opens>org.test.myClass</opens>
    <uses>org.test.spi.serviceProvider</uses>
    <provides>org.test.spi.serviceProvider with org.test.spi.serviceProviderImpl</provides>
  </moduleInfo>
</module>
```

**Comment by gunnarmorling** [comment]
Thanks for the report. Really a weird oversight. Would you be interested
perhaps in sending a pull request for implementing this?

>

**Comment by xinyingho** [comment]
Ok, doing it.

However, I've met an unexpected issue. It looks like moditect is configured the latest JavaParser-Core library, and it has changed its API a bit with v3.9.1: StaticJavaParser has been deleted as everything has been consolidated into JavaParser.

Nothing big, my PR should be ready very soon.

**Comment by xinyingho** [comment]
PR ready for review

**Comment by matozoid** [comment]
@xinyingho oh, here is the motivation for the JavaParser downgrade. Actually, `StaticJavaParser` has been *introduced* lately, here is the PR for it: https://github.com/moditect/moditect/pull/106
