### ISSUE TITLE
Ability to specify "--bind-services" option for create-runtime-image goal.

### ISSUE THREAD

**Issue by jaygazula27** [moditect/moditect#129]
This plugin has been so useful for modular applications, but I hit a snag recently when one of my dependencies was trying to use the service provider functionality.
Would it be possible to add the `--bind-services` flag as part of the create-runtime-image goal? 

Documentation is provided here: https://docs.oracle.com/javase/9/tools/jlink.htm#JSWOR-GUID-CECAC52B-CFEE-46CB-8166-F17A8E9280E9

Thank you!

**Comment by gunnarmorling** [comment]
Happy to hear ModiTect is useful to you, thanks! Re your suggestion, sure, that sounds reasonable. Would you be interested in sending a PR for it?

**Comment by jaygazula27** [comment]
Sure! Just sent the PR.

**Comment by gunnarmorling** [comment]
Sweet, thx. Not sure yet when we'll do the next release (CC @siordache); in the meantime you could simply build from source of course.

**Comment by jaygazula27** [comment]
Yep, sounds good. Thank you!
