### ISSUE TITLE
Support moduleInfo exports to a set of modules

### ISSUE THREAD

**Issue by fax4ever** [moditect/moditect#148]
If I try to do something like the following:

``` xml
<exports>
  org.hibernate.search.*.impl to org.hibernate.engine;
  *;
</exports>
```

Moditects creates all the exports to the given module.
One exports to the given module for each package matching the pattern. 
That is great!

But if I try this:

``` xml
<exports>
  org.hibernate.search.*.impl to org.hibernate.engine,org.hibernate.search.mapper.orm;
  *;
</exports>
```

I got the error:

``` bash
Execution add-module-infos of goal org.moditect:moditect-maven-plugin:1.0.0-SNAPSHOT:add-module-info failed: Encountered unexpected token: "," ","
[ERROR]     at line 1, column 21.
[ERROR] 
[ERROR] Was expecting:
[ERROR] 
[ERROR]     <EOF>
```

Shall we try to support that?

**Comment by gunnarmorling** [comment]
Thanks for the report and the fix. Indeed this has been a shortcoming for a long time.
