### ISSUE TITLE
add-module-info assumes current project artifact path

### ISSUE THREAD

**Issue by dwhitla** [moditect/moditect#151]
AddModuleInfoMojo attempts to add module-info to the JAR at `buildDirectory.toPath().resolve( artifactId + "-" + version + ".jar" );`. This assumes the value of `${project.build.finalName}` and is very often not correct.
Please use `${project.build.finalName}` instead. It also assumes that this artifact is found in `${project.build.directory}` regardless of the value of `outputDirectory` supplied to the `maven-jar-plugin`. This path should be exposed as a configuration parameter.

**Comment by gunnarmorling** [comment]
Good idea; would you like to send a PR for this perhaps?

**Comment by dwhitla** [comment]
I will take a look at it.
