### ISSUE TITLE
Update version to snapshot after release

### ISSUE THREAD

**Issue by gunnarmorling** [moditect/moditect#154]
As discussed in https://github.com/moditect/moditect/pull/153; // CC @aalmiray

**Comment by aalmiray** [comment]
The current release workflow triggers when a tag such as `v1.2.3` is created. This allows using the manual workflow `trigger.yml` or pushing a matching tag by any other means, that is, we have 2 ways to trigger the release.

In contrast, kcctl uses a single workflow (combining tag & release) as seen at https://github.com/kcctl/kcctl/blob/93e60e967189642747f90b512668db46c0273a77/.github/workflows/release.yml

This workflow requires 2 inputs: the release version, and the next version. The 2nd number is optional and will be automatically calculated.

@gunnarmorling: should we use a single workflow like kcctl? Or should we keep 2 options to trigger a release as it is right now? Or rephrasing, how comfortable would yo be if releases could only be posted by trigger a GH workflow and no other automated way?

**Comment by gunnarmorling** [comment]
> how comfortable would yo be if releases could only be posted by trigger a GH workflow and no other automated way?

Very comfortable, as I would always use that option only anyways, instead of locally creating a tag and then pushing it. +1 for a single workflow triggered manually in the GH UI.
