### ISSUE TITLE
Java version parsing fails with some JDKs, module-info.java is not found

### ISSUE THREAD

**Issue by yrodiere** [moditect/moditect#162]
With some JDKs, System property `java.version` returns a single number, for example OpenJDK 17 early-access builds use `17`.

This means the following parsing code in Moditect will fail:

https://github.com/moditect/moditect/blob/d2cc464c4abf853d393c05010fd6a3d0de776580/core/src/main/java/org/moditect/internal/parser/JavaVersionHelper.java#L28-L30

https://github.com/moditect/moditect/blob/d2cc464c4abf853d393c05010fd6a3d0de776580/core/src/main/java/org/moditect/internal/parser/JavaVersionHelper.java#L70-L75

As a result, #141 reappears: Moditect is unable to detect `module-info.java` if it's in `versions/<some-version>`.

```
[INFO] --- moditect-maven-plugin:1.0.0.RC2:add-module-info (add-module-infos) @ hibernate-search-util-common ---
writing to /home/yrodiere/workspaces/main/hibernate-search/util/common/target/moditect/org.hibernate.search.util.common/versions/9/module-info.java
[WARNING] The java version 17 cannot be parsed as ^(\d+)\.(\d+)\.(\d+).*
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Hibernate Search Root POM 6.2.0-SNAPSHOT:
[INFO] 
[INFO] Hibernate Search Root POM .......................... SUCCESS [  1.192 s]
[INFO] Hibernate Search Build - Config .................... SUCCESS [  3.128 s]
[INFO] Hibernate Search Build - Surefire Extension ........ SUCCESS [  1.637 s]
[INFO] Hibernate Search Parent POM for Internal Artifacts . SUCCESS [  1.085 s]
[INFO] Hibernate Search Utils - Internal - Test - Common .. SUCCESS [  4.502 s]
[INFO] Hibernate Search Utils - Internal - Test - ORM ..... SUCCESS [  1.057 s]
[INFO] Hibernate Search Parent POM for Public Artifacts ... SUCCESS [  1.109 s]
[INFO] Hibernate Search Utils - Common .................... FAILURE [  7.770 s]
[INFO] Hibernate Search Engine ............................ SKIPPED
[... ommitted for brevity ...]
[INFO] Hibernate Search Reports ........................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  21.997 s
[INFO] Finished at: 2022-03-31T15:28:32+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.moditect:moditect-maven-plugin:1.0.0.RC2:add-module-info (add-module-infos) on project hibernate-search-util-common: Execution add-module-infos of goal org.moditect:moditect-maven-plugin:1.0.0.RC2:add-module-info failed: Couldn't parse /home/yrodiere/workspaces/main/hibernate-search/util/common/target/moditect/org.hibernate.search.util.common/module-info.java -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :hibernate-search-util-common
```

**Comment by aseovic** [comment]
@gunnarmorling This issue seems to be blocking us as well, as it's causing a number of our CI builds to fail, depending on which JDK version they use. 

If the proposed fix can be reviewed and merged, and the new release with the fix pushed out to Maven Central, it would be greatly appreciated. Thanks!

**Comment by gunnarmorling** [comment]
Thanks for the reminder! I'll take a look in the course of this week.

**Comment by yrodiere** [comment]
> Thanks for the reminder! I'll take a look in the course of this week.

@gunnarmorling bump? :)

**Comment by gunnarmorling** [comment]
Hey @yrodiere, sorry, this fell completely through the cracks. Just merged your PR, thanks a lot. Do you need a formal release with this too?

**Comment by yrodiere** [comment]
Thanks!

Personally I'm not currently using JDKs that cause this bug, but @aseovic seems to have forked moditect to work around the problem. So it's not urgent, but I think a release would be a good idea at some point :)

**Comment by aseovic** [comment]
Yeah, I merged this change and several other fixes that we needed into my fork, as I didn't want to bug @gunnarmorling too much.

It would be nice to get all the fixes in and the official 1.0 release out, though, so I can stop maintaining my fork.

**Comment by gunnarmorling** [comment]
Hey Alexs, could you create PR with your additional fixes, so we could
integrate them into ModiTect proper?

**Comment by yrodiere** [comment]
> could you create PR with your additional fixes

@gunnarmorling You may not have seen the edited part of @aseovic's message since you're replying from an email client, but he already did:

> I believe all of my changes are already captured by #168, #170 and #172.

**Comment by gunnarmorling** [comment]
Doh, good catch and call-out, @yrodiere! Appreciate it 🙏 . @aseovic, thanks a lot for those, will check them out ASAP.
