### ISSUE TITLE
Invocation of jdeps failed when running Github Actions

### ISSUE THREAD

**Issue by Meodinger** [moditect/moditect#165]
I'm using moditect to create multi-release `Jsoup`. The tests passed in my local machine but failed when running Github Actions due to moditect: Invocation of jdeps failed at [this PR](https://github.com/jhy/jsoup/pull/1744). 

Can anybody help me?

**Comment by Meodinger** [comment]
Sorry, me make mistake, forget to ignore jsr305

**Comment by Meodinger** [comment]
But maybe we could print the jdeps error output in the exception

**Comment by gunnarmorling** [comment]
Sounds good; fancy sending a PR?

**Comment by Meodinger** [comment]
I'll give a try
