### ISSUE TITLE
Allow explicit exclusion of dependencies from the jdeps module path

### ISSUE THREAD

**Issue by aseovic** [moditect/moditect#169]
At the moment, Moditect simply uses `MavenProject.getArtifacts` to determine the module path to use when invoking `jdeps` to create `module-info`. While this is generally correct behavior, there are situations when it would be useful to be able to explicitly exclude some dependencies from the module path.

For example, when generating `module-info` for a module that shades one or more internal dependencies without relocation, not excluding the shaded dependencies from the module path leads to superfluous "split packages" warnings, as the same classes/packages exist in both artifacts. Excluding shaded dependency eliminates those warnings.

**Comment by rickardoberg** [comment]
I'm mostly using Moditect for shaded artifacts (Neo4j and gRPC), and it's a bit of a pain because of the issue mentioned here. So far I've had to use two separate Maven modules to workaround, which is not ideal. Is this fix still not merged in? What's the plan?
