### ISSUE TITLE
AddModuleInfo does not generate reproducible archives

### ISSUE THREAD

**Issue by aalmiray** [moditect/moditect#185]
The `org.moditect.commands.AddModuleInfo` class does not generate reproducible archives because the `module-info.class` entry does not have a timestamp matching the rest of the archive which might have been configured as reproducible.

https://github.com/moditect/moditect/blob/5e4f1ccf50d371de71ffde2d0b2877f7f8f1744d/core/src/main/java/org/moditect/commands/AddModuleInfo.java#L53 should take an additional parameter with the given timestamp, defaulting to the begin of the epoch.

Follow the same behavior when parsing the timestamp as https://github.com/apache/maven-archiver/blob/0f66795c8d1cbcc9f767b6e23b72e029040481b7/src/main/java/org/apache/maven/archiver/MavenArchiver.java#L862-L901

**Comment by agentgt** [comment]
I'm not sure why but this still does not work for me even 1.0.0.Final.

I have a project with a module that uses moditect:

https://github.com/jstachio/jstachio/tree/main/compiler/apt

```
mvn clean install
mvn clean verify artifact:compare
```

If I remove the moditect add-module

https://github.com/jstachio/jstachio/tree/main/compiler/apt/pom.xml

I get reproducible builds.

All my other modules that do not use moditect are fine.

diffoscope says all the files are identical but that the jar zip differs.

**Comment by agentgt** [comment]
Yeah somewhere you guys are using the local time zone:

```
     6159  12-23-2022 00:56   io/jstach/apt/prism/RawPrism.class
      296  12-23-2022 00:56   io/jstach/apt/prism/package-info.class
      248  12-22-2022 19:56   module-info.class
```

My timestamp is: 1671757006

Which is 

```
jshell> import java.time.*;

jshell> Instant.ofEpochSecond(1671757006).atOffset(ZoneOffset.UTC)
$5 ==> 2022-12-23T00:56:46Z
```

And not: `12-22-2022 19:56` which is my local time at that epoch (EDT).

Even though that is wrong I'm not sure why it would not be reproducible.

**Comment by agentgt** [comment]
Ignoring the whole timezone issue which isn't really the problem.

I think you need to use: https://github.com/codehaus-plexus/plexus-archiver instead of the raw JDK filesystem abstraction.

https://github.com/moditect/moditect/blob/41784cb65f9a564012212ba94307ad98455d789d/core/src/main/java/org/moditect/commands/AddModuleInfo.java#L115
