### ISSUE TITLE
maven plugin error after upgrading jackson to 2.15.1 from 2.14.2

### ISSUE THREAD

**Issue by stevehu** [moditect/moditect#200]
Here is the error in the Maven build. 

```
Execution add-module-infos of goal org.moditect:moditect-maven-plugin:1.0.0.Final:add-module-info failed: Module com.fasterxml.jackson.core not found, required by com.fasterxml.jackson.dataformat.yaml
```

Let me know if any context information is needed. Thanks.

**Comment by aalmiray** [comment]
The error message suggests that jackson-core is no available as compile or runtime dependency, but it should unless explicitly excluded.

**Comment by stevehu** [comment]
The Jackson 2.15.0 and 2.15.1 releases are the problem. After upgrading to 2.15.2 and all problems are gone. Thanks a lot for your help.
