### ISSUE TITLE
jdepsExtraArgs gotcha

### ISSUE THREAD

**Issue by hgschmie** [moditect/moditect#209]
This works:

```xml
 <jdepsExtraArgs>
    <arg>--multi-release=11</arg>
</jdepsExtraArgs>
```

This does not:

```xml
 <jdepsExtraArgs>
    <arg>--multi-release 11</arg>
</jdepsExtraArgs>
```

and what is more confusing is that the error message lists out the failed command (jdeps ...) and if you cut and paste it, it works fine.

It seems that either the `<arg>` tag is not properly split on whitespace or should throw an error if it contains a whitespace.

**Comment by dwhitla** [comment]
```
<jdepsExtraArgs>
    <arg>--multi-release</arg><arg>11</arg>
</jdepsExtraArgs>
```
works and is consistent with lots of other Maven plugin configurations taking an array of args which will be joined with whitespace.
