### ISSUE TITLE
Support for new Compression vars

### ISSUE THREAD

**Issue by WarWolfen** [moditect/moditect#213]
Hi!

Since Java 21 the compression for JLink has changed. I get the error/warning in my build:
[ERROR] Warnung: Das Argument 2 für --compress ist veraltet und wird möglicherweise in einem zukünftigen Release entfernt
"Argument 2 (1,0) is deprecated and might be removed in a future release" (my translation)

In my pom.xml I have:
< compression >2< / compression >

In the future, this seems to change to "zip0" to "zip9" instead of the currently used numbers. I found that after some searching somewhere on stackoverflow.

**Comment by WarWolfen** [comment]
https://mail.openjdk.org/pipermail/core-libs-dev/2023-February/100453.html

**Comment by aalmiray** [comment]
The value for `compress` may be `<0|1|2|zip-[0-9]>[:filter=<pattern-list>]`

**Comment by WarWolfen** [comment]
In this case, I am doing something else wrong:
![image](https://github.com/moditect/moditect/assets/16292643/94470ba8-0a3c-4c2e-af2b-f732621f825b)

**Comment by aalmiray** [comment]
That is because the currently published version of the plugin expects an `Integer`. The fix for this issue migrates the type to `String`. You'll have to wait til the next release.

**Comment by WarWolfen** [comment]
Great, thank you!
