### ISSUE TITLE
add-module-info no longer allows replacing the existing module-info in a jar

### ISSUE THREAD

**Issue by ekpeters** [moditect/moditect#215]
I've a handful of 3rd party jars where I've had to replace the module-info they ship with to fix omissions or errors in the module-info.  I'd used to use Moditect to patch them at build time, but the current release (1.0.0.Final) of Moditect now throws an error if you try to replace the module-info.  You can set it to treat this as a warning - which it does kindly warn you, and then skip processing the file.

My option appears to be that I need to delete the module-info from the jar before passing it to moditect, requiring me to go to extra steps just to add a missing require or export to someone's module-info (because, lets face it, not everyone understands module-info files).

**Comment by aalmiray** [comment]
This should be possible now that #230 is merged
