### ISSUE TITLE
`add-module-info` of moditect-maven-plugin fails for multi-module projects, Shade plugin with "xxx-[version].jar is already modular"

### ISSUE THREAD

**Issue by cowtowncoder** [moditect/moditect#221]
After version 1.0.0-rc2 up to and including 1.1.0, Jackson base modules project Maven build has failed as shown by PR https://github.com/FasterXML/jackson-modules-base/pull/228 (trying to remove version override): error message is:

```
[ERROR] Failed to execute goal org.moditect:moditect-maven-plugin:1.1.0:add-module-info (add-module-infos) on project jackson-module-afterburner: File jackson-module-afterburner-3.0.0-SNAPSHOT.jar is already modular -> [Help 1]
[ERROR] 
```

Failing project (mart of multi-module project) also uses Maven shade plugin (version 3.5.1), which might be relevant.

**Comment by aalmiray** [comment]
There are 2 settings you may try: `overwriteExistingFiles` and `failOnWarning` to change the default behavior.

**Comment by cowtowncoder** [comment]
Thank you @aalmiray I'll give those a try.

**Comment by cowtowncoder** [comment]
But `failOnWarning` seems like it might just work...

**Comment by cowtowncoder** [comment]
@aalmiray Not sure if there is a problem to resolve any more; feel free to close if not.
