### ISSUE TITLE
NullPointerException on create-runtime-image goal whith no goals specified

### ISSUE THREAD

**Issue by ggam** [moditect/moditect#33]
When using the `create-runtime-image` goal with no `<modules>` set, a NullPointerException is thrown at https://github.com/moditect/moditect/blob/e0b3fa191baacf8e201d9dadbc555cf3e27867cb/core/src/main/java/org/moditect/commands/CreateRuntimeImage.java#L68

That line should first check wether modules have been set before adding the `--add-modules` parameter.

**Comment by gunnarmorling** [comment]
Thanks, good catch! Would you like to send a PR?

**Comment by ggam** [comment]
Sure. I have doubts regarding the expected behavior though. Is the `--add-modules` parameter required for jlink? In that case, I guess the goal execution should just finish with a descriptive and clear error message, right?

**Comment by gunnarmorling** [comment]
Yes, at least one root module must be given:

> jlink --help
> Usage: jlink <options> --module-path <modulepath> --add-modules <module>[,<module>...]
> Possible options include:
>      --add-modules <mod>[,<mod>...]    Root modules to resolve
> ...

So as you say an error should be raised if not at least one module is given.

Thanks a lot!
