### ISSUE TITLE
Maven plugin throws NullPointerException if dependencyManagement is not defined

### ISSUE THREAD

**Issue by rjpfonseca** [moditect/moditect#40]
In the 'add-module-info' goal, if the pom or any of its parents does not define a \<dependencyManagement\> section, then the plugin throws a NullPointerException if it needs to search for the artifact dependencies of one of the defined modules. The [attached pom file](https://github.com/moditect/moditect/files/1609263/pom.zip) can be used to trigger the exception when executed with 'mvn package'.

In your code, there are two places where you are retrieving the dependency management from the project object: [ModuleInfoGenerator](https://github.com/moditect/moditect/blob/7f210838714856b2ee5cec1889e32ba535c26fb5/maven-plugin/src/main/java/org/moditect/mavenplugin/generate/ModuleInfoGenerator.java#L207) and [AddModuleInfoMojo](https://github.com/moditect/moditect/blob/7f210838714856b2ee5cec1889e32ba535c26fb5/maven-plugin/src/main/java/org/moditect/mavenplugin/add/AddModuleInfoMojo.java#L205l). I'm not familiar with maven plugin development and its current best practices, and I couldn't find anything online on what's the appropriate way to get all of a project's direct dependencies. Should one get all the dependencies from MavenProject::getDependencies and then somehow combine those with any present via MavenProject::getDependencyManagement in case it exists? Maybe there's no general guidance and it depends on what a plugin wants to do. What do you think could be done in your case?

**Comment by gunnarmorling** [comment]
Done.
