### ISSUE TITLE
Support adding --ignore-signing-information

### ISSUE THREAD

**Issue by pupeno** [moditect/moditect#51]
When jliking, it'd be nice to have a way to add --ignore-signing-information to the command to avoid:

```
[INFO] --- moditect-maven-plugin:1.0.0.Beta1:create-runtime-image (create-runtime-image) @ dashman ---
[ERROR] Error: signed modular JAR C:\Users\pupeno\Documents\Dashman\code\dashman\target\modules\bcprov-jdk15on-1.59.jar is currently not supported, use --ignore-signing-information to suppress error
```

**Comment by gunnarmorling** [comment]
Good idea; perhaps you'd be interested in creating a pull request for this, @pupeno?

**Comment by malikoski** [comment]
i made a PR

**Comment by malikoski** [comment]
Updated README.MD.

**Comment by malikoski** [comment]
Waiting merge...

**Comment by gunnarmorling** [comment]
PR is merged. Thanks, @malikoski!

**Comment by pupeno** [comment]
Thank you. I'm sorry I didn't pitch in, I stopped using moditec when I had to go back to Java 8. It looks like I'm back on Java 10 now.
