### ISSUE TITLE
Build error on JDK8 due to the use of a field only available since Java 9

### ISSUE THREAD

**Issue by beikov** [moditect/moditect#55]
The use of the MULTI_RELEASE manifest attribute name leads to an error when executing a build on JDK 8. I must have missed that when testing #53

**Comment by beikov** [comment]
Also, I just realized, that having JARs with an existing MANIFEST.MF leads to an exception when specifying the jvm version element because the ZipFileSystem reports that META-INF/MANIFEST.MF already exists.

Unfortunately, even though the module-info.class file is now in META-INF, Jandex will still fails to index the JAR, so this feature will not help with that problem.

**Comment by gunnarmorling** [comment]
Fixed.

**Comment by gunnarmorling** [comment]
> Unfortunately, even though the module-info.class file is now in META-INF, Jandex will still fail to index the JAR, so this feature will not help with that problem.

Yes, that's a known issue. It has been fixed in Jandex some time ago (by simply ignoring all module-info.class files), but I reckon you cannot easily upgrade depending on your environment.
