### ISSUE TITLE
Running moditect on JDK 7 / JDK 8

### ISSUE THREAD

**Issue by lukehutch** [moditect/moditect#62]
I have been trying to get moditect to work on JDK 7 / JDK 8, to create jars that work on those releases, but also work as modules on Java 9+. I have discovered that this works fine, as long as I build on JDK9+, in Java 7 compatibility mode.

If I build in JDK 7 or 8, the error I get is:

[ERROR] Failed to execute goal org.moditect:moditect-maven-plugin:1.0.0.Beta1:add-module-info (add-module-infos) on project fast-classpath-scanner: Execution add-module-infos of goal org.moditect:moditect-maven-plugin:1.0.0.Beta1:add-module-info failed: A required class was missing while executing org.moditect:moditect-maven-plugin:1.0.0.Beta1:add-module-info: java/lang/module/FindException

I don't know of a way to get just one Maven plugin to run with a different JDK version (e.g. build on JDK 7 or 8 to ensure compatibility, but run moditect in JDK10 or later), but if it's not much work to support running moditect on older JDKs, it may be useful to be able to do so. (Moditect uses bytecode compilation internally, and the source doesn't yet use "var" style assignments or anything, so maybe both forwards and backwards compatibility is easy to support?)

**Comment by gunnarmorling** [comment]
Hey Luke, how did you invoke the plug-in exactly?

The mode that takes a module-info contents verbatim (`moduleInfoSource`) should work on JDK < 9; if it actually doesn't, then I'd consider that a bug. If you derive the module info descriptor though (`moduleInfo`), then this indeed will only run on JDK 9 as this uses some JDK 9 APIs under the hood.

**Comment by lukehutch** [comment]
Hi @gunnarmorling -- just wondering if you had a chance to look at this? I just realized I broke JDK 7 compatibility in my project in the last couple of releases, and didn't notice, because I had to disable the Travis JDK 7 and 8 builds, because I get an error from Moditect building under those versions. You can see how I'm incorporating Moditect in my `pom.xml` file.

**Comment by gunnarmorling** [comment]
Hey @lukehutch, sorry, didn't look into it yet, am heads down into some other things these days. But I'll get to it eventually. Is it still the case that I can reproduce the issue by running your master branch with JDK 7 or 8?

**Comment by lukehutch** [comment]
@gunnarmorling That should be the case, yes. I haven't touched the Moditect config since filing this bug. I had to disable my Travis build rules for JDK 7 and JDK 8 just to prevent getting Travis failure messages on every build.

**Comment by lukehutch** [comment]
I finally understand what you meant by "(`moduleInfo`)" in your previous comment. I didn't realize you were referring to an XML tag `<moduleInfo>`. This is in fact how I am currently invoking the plugin using the following rules, inside `<project><build><plugins>`:

```xml
			<plugin>
				<groupId>org.moditect</groupId>
				<artifactId>moditect-maven-plugin</artifactId>
				<version>1.0.0.Beta1</version>
				<executions>
					<execution>
						<id>add-module-infos</id>
						<phase>package</phase>
						<goals>
							<goal>add-module-info</goal>
						</goals>
						<configuration>
							<overwriteExistingFiles>true</overwriteExistingFiles>
							<module>
								<moduleInfo>
									<name>io.github.lukehutch.fastclasspathscanner</name>
									<exports>
										io.github.lukehutch.fastclasspathscanner;
										io.github.lukehutch.fastclasspathscanner.classloaderhandler;
										io.github.lukehutch.fastclasspathscanner.matchprocessor;
										io.github.lukehutch.fastclasspathscanner.scanner;
										io.github.lukehutch.fastclasspathscanner.typesignature;
										io.github.lukehutch.fastclasspathscanner.utils;
									</exports>
								</moduleInfo>
							</module>
						</configuration>
					</execution>
				</executions>
			</plugin>
```

Therefore, according to your comment, there is no bug currently. It's a shame though that this isn't backwards compatible, through reflection or ASM, since the main usecase for something like this would be for adding a `module-info.class` file to legacy code, and it's not always possible to bump the JDK version to 9+ in this case.

**Comment by lukehutch** [comment]
I switched to using `<modInfoSource>`, and Moditect now works fine on JDK 8. My apologies for not reading the docs closely enough / not understanding them!

**Comment by gunnarmorling** [comment]
Ok, glad to hear. Sorry for not being clearer that I meant the XML element `<moduleInfoSource>`. Indeed only that one currently works with Java < 9; it'd be nice to also have support for the semi-automatic descriptor generation via `<moduleInfo>`, but it's implementation currently uses some Java 9 classes, more specifically it uses jdeps under to hoods to create a "candidate descriptor" which then is amended and tuned by ModiTect. This could be replaced with custom code of course, although it seems like the clock is running for Java 8, so the value of this implementation diminishes over time.

**Comment by lukehutch** [comment]
Fair enough re. the clock running out. I'm sure we'll still see people sticking to their guns and refusing to move to modular JDK 5 or 7 years from now though :-)  With the 6-month release cycles coming up, things are going to start moving really, really fast...

You have indeed documented the behavior, and there is a JDK < 9 option available in `<moduleInfoSource>` / `<moduleInfoFile>`, so I'll close this. Thanks for your responses!

**Comment by lukehutch** [comment]
PS @gunnarmorling thanks for creating this incredibly valuable library!

**Comment by gunnarmorling** [comment]
> PS @gunnarmorling thanks for creating this incredibly valuable library!

Thanks, that's nice to hear and happy that the tool is useful to you.

Btw. I'm definitely open towards supporting `<moduleInfo>` also on JDK < 9, it's "only" a question of finding the time. ModiTect is a small effort I'm doing on the side if I find a minute, and there's several other things I have in mind which I'd like to add... :)

**Comment by lukehutch** [comment]
I imagine one of the big usecases for ModiTect at this point is modularizing old libraries, or libraries that have to work with old codebases, or run on old JREs. But actually for this usecase, the `<moduleInfo>` syntax is not necessarily any easier than just creating a `module-info.java` file, and then pointing `<moduleInfoFile>` at it. (I had to put it in `resources/` though, it can't go in a source directory in pre-JDK9 builds.) I'm sure you have some advanced features planned, but for this simple usecase, there's probably no rush to support `<moduleInfo>` or old JDKs.

**Comment by lukehutch** [comment]
@gunnarmorling Any chance you can please push out a new release? I got yet another report of problems from third party runtime environments dying when they find a module-info.class in the root of the jar. (This time it's Tomcat BCEL, called by Apache Catalina.) This is probably the third or fourth time I have run into this. I could manually move the module-info.class into a versioned section of the jar, but I'd rather automate it with the new Moditect features. Thanks!

**Comment by lukehutch** [comment]
(Moving discussion to #67, since it is more relevant)
