### ISSUE TITLE
module-info.class even in META-INF/versions might break some older tooling

### ISSUE THREAD

**Issue by bjakke** [moditect/moditect#71]
For example https://stackoverflow.com/questions/46878035/error-scanning-entry-meta-inf-versions-9-org-apache-logging-log4j-util-stackloca .

Therefore in README.md the part

> This is to ensure a maximum of compatibility with older libraries scanning class files that may fail when encountering the module-info.class file (and chances are much lower that such tool will look for class files under META-INF/versions/...).

could maybe mention that some do search there. And the other way: I could see some tools fail to notice the module-info.class from the META-INF/versions part.

Anyway I want to greatly thank you for making this plugin, as now it is at least easy for me to create 2 output jars out of older libraries such as one being <=8 and another 9+ , by running the plugin after the main build phase to create a secondary one that has the module-info in the root.

**Comment by gunnarmorling** [comment]
Yes, indeed it's not perfect, but I think chances of issues are reduced compared to having the module descriptor in the root dir.

Happy to hear you find the plug-in useful.

**Comment by gunnarmorling** [comment]
Turns out putting the descriptor under _META-INF/versions_ wasn't a good idea for other reasons (see discussion in #67). So I've reverted that part and and also updated the docs to reword that section a bit.
