### ISSUE TITLE
Possibility to skip plugin execution (or don't run add-module-info goal if POM type is 'pom')

### ISSUE THREAD

**Issue by taranion** [moditect/moditect#81]
Could you provide a possibility to skip the plugin execution by configuration?

I am defining the plugin (using the add-module-info goal) in a parent POM, which does not generate a jar itself (because it is of type 'pom'). I get the error
Couldn't find file _XXX/target/XXX.jar._ Run this goal for the project's JAR only after the maven-jar-plugin

**Comment by gunnarmorling** [comment]
That sounds like a reasonable suggestion. Would you be interested in
creating a pull request with this change?

>

**Comment by taranion** [comment]
Ok, that was more straight forward than I expected. PR is awaiting your inspection :)

**Comment by gunnarmorling** [comment]
Done.
