### ISSUE TITLE
When paired with a jar modifier a file in use error is thrown

### ISSUE THREAD

**Issue by GedMarc** [moditect/moditect#87]
[ERROR] Failed to execute goal org.moditect:moditect-maven-plugin:1.0.0.Beta2:add-module-info (add-module-infos) on proj
ect guice: Execution add-module-infos of goal org.moditect:moditect-maven-plugin:1.0.0.Beta2:add-module-info failed: Couldn't replace C:\AESoft\Programs\ThirdParty\guice\guice-core\target\guice-0.0.0_0-SNAPSHOT.jar with modularized version: C:\AESoft\Programs\ThirdParty\guice\guice-core\target\guice-0.0.0_0-SNAPSHOT.jar: 

The process cannot access the file because it is being used by another process. -> [Help 1]    

https://github.com/GedMarc/guice-core
mvn install -Pjdk8

Offending plugin : JarJar

**Comment by gunnarmorling** [comment]
Hey, so it was not an issue with ModiTect after all?

**Comment by GedMarc** [comment]
Was way too specific circumstances for it to have been :)

1) Only on windows, centos and ubuntu not affected
2) Only when used with JarJar
3) Only when placed after the JarJar plugin in a pom file

The JarJar plugin fails on reading the module-info with a null exception (not able to read jdk9^ class files yet a presume) and then holds the locks on the jar file, but only on windows xD
