### ISSUE TITLE
Support multi-threaded Maven builds

### ISSUE THREAD

**Issue by vsilaev** [moditect/moditect#95]
Here is what Maven reports when invoked in multi-threaded mode (say, "mvn -T 9 clean install") when Moditect plugin is used:

[WARNING] The following plugins are not marked @threadSafe in Tascalate JavaFlow / Tools / Apache Maven:
[WARNING] org.moditect:moditect-maven-plugin:1.0.0.Beta2
[WARNING] Enable debug to see more precisely which goals are not marked @threadSafe.

If Moditect is thread-safe by nature than it makes sense to add aforementioned annotation...

**Comment by jponge** [comment]
I have a similar warning when building Mutiny with multiple threads:

```
[WARNING] *****************************************************************
[WARNING] * Your build is requesting parallel execution, but project      *
[WARNING] * contains the following plugin(s) that have goals not marked   *
[WARNING] * as @threadSafe to support parallel building.                  *
[WARNING] * While this /may/ work fine, please look for plugin updates    *
[WARNING] * and/or request plugins be made thread-safe.                   *
[WARNING] * If reporting an issue, report it against the plugin in        *
[WARNING] * question, not against maven-core                              *
[WARNING] *****************************************************************
[WARNING] The following plugins are not marked @threadSafe in SmallRye Mutiny - Core library:
[WARNING] org.moditect:moditect-maven-plugin:1.0.0.RC2
[WARNING] Enable debug to see more precisely which goals are not marked @threadSafe.
[WARNING] *****************************************************************
```

It'd be great to have the plugin thread-safe 👍

**Comment by gunnarmorling** [comment]
Thanks for the report, @vsilaev and @jponge. I'm not totally sure what it entails to make a Maven plug-in thread-safe, but for sure worth exploring and making it happen. IF somebody from the community wanted to take the lead on this, that'd be awesome.

**Comment by jfallows** [comment]
@gunnarmorling please take a look at the proposed fix in the linked PR.

**Comment by agentgt** [comment]
@gunnarmorling 

Take a look at: https://cwiki.apache.org/confluence/display/MAVEN/Parallel+builds+in+Maven+3
Specifically the thread safety checklist.

I took a very quick glance ripgrepping the code looking for any mutable static singletons and I could not find any. 

However I didn't examine how you use ASM. ASM thread safe info is here:
https://asm.ow2.io/faq.html#Q13

So in theory @jfallows PR of just marking the plugin threadsafe will probably be OK provided you synchronize where you write the classes with ASM.

**Comment by agentgt** [comment]
Actually this might be problematic but problematic in general depending on what happens with class loading:

https://github.com/moditect/moditect/blob/56fdfc2ef89ed9ba4b04e8a57815464709ad9b03/core/src/main/java/org/moditect/internal/compiler/ModuleInfoCompiler.java#L50

**Comment by gunnarmorling** [comment]
@agentgt, thx for commenting. Any fixes will be more than welcomed. I don't have an awful lot of time to spend on ModiTect these days unfortunately. More than happy to review and merge PRs if they are managable, though.

**Comment by agentgt** [comment]
@gunnarmorling I can probably look into next month. I'm rather slammed myself.
